language: node_js
node_js:
- '6'
env:
- CXX=g++-4.8 NODE_ENV=production
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
  - node_modules
script:
- npm install --dev
- npm run lint --silent
- npm run build
deploy:
  provider: releases
  api_key:
    secure: BR541kNK7rvaFRdUpK1UOwx/BW4WCdYwklMrtewMx0Zro9266bo+R4HeWkygWPFwZQhWNpoigLe9ByjdkTBXMytkp4WkI7hKXdmgSgJihF3cNf6DZEdmri7BDG4+HkhwfJhsmpDCbSQN0Ah1OtBEwMDIlCmdMijv9B7D3ngcQFjnz7fx/8rWK0ST1jKLVS3ctF3iq2JiZHhIVi3c2QGNcPVFrWTDzNSRXp+CBZKa2a/KD7W0Zxe2Mpd7Fq/oYni/iKzKn4MT16V1JXBajoaLNNgKL3nywOObvf5EJLsjoLxKxImli9/ogLDt5vpK15G3jU5U8uOl30ddWqaci1SojInu3ihxwiPWTr4T7nWTEc6fIpTvYxmDeQDM7ddel4ldtgTMsAUnuVCc88rXWgyvyYezeDdBxuy7uCvFGpqW/3UJx9EDrczkEmTz4bQiH4j1sDGKDC5Xc6I0UIDLx4yZOAibvSF/EEyRjTt0+ho0JRE41xkFmUDItpCFEWgMjWsGaS0QV9Cbpi7R+r+2Y3FYryZ+oGijsYUyv3AdliArxtnuZBbkzGOXXrbpJkUHK94N2vFyQktKgkpqmnCLxL1BdKgjz/Utd94OZ5rSt1z9Ao/oIBjE73Cp9yVtpqfYafm+Ymp6geBqOMNdRtne3ZKtZZDdfDoNc0WjN7YsTTkAjr8=
  skip_cleanup: true
  file: build/*.zip
  file_glob: true
  on:
    repo: japanesemediamanager/jmmserver-webui
    tags: true
