/**
 * Events are actions that are used to invoke sagas but don't get processed in the reducer usually
 */

export default {
  GLOBAL_ALERT: 'EVENT_GLOBAL_ALERT',
  DASHBOARD_LOAD: 'EVENT_DASHBOARD_LOAD',
  DASHBOARD_QUEUE_STATUS: 'EVENT_DASHBOARD_QUEUE_STATUS',
  DASHBOARD_RECENT_FILES: 'EVENT_DASHBOARD_RECENT_FILES',
  PAGE_IMPORT_FOLDERS_LOAD: 'EVENT_PAGE_IMPORT_FOLDERS_LOAD',
  PAGE_LOGS_LOAD: 'EVENT_PAGE_LOGS_LOAD',
  PAGE_SETTINGS_LOAD: 'EVENT_PAGE_SETTINGS_LOAD'
};
