name: Lint-PR
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    name: Lint check PR

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install pnpm and Node.js
        uses: pnpm/setup@v1
        with:
          version: 11
          runtime: node@24
          cache: true

      - name: Lint
        run: pnpm lint --quiet
