name: Lint-PR
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    name: Lint check PR

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint --quiet
