name: opencode

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  opencode:
    if: |-
      github.event.comment.user.type != 'Bot' &&
      (
        github.event.comment.author_association == 'OWNER' ||
        github.event.comment.author_association == 'MEMBER' ||
        github.event.comment.author_association == 'COLLABORATOR'
      ) &&
      (
        contains(github.event.comment.body, '/oc') ||
        contains(github.event.comment.body, '/opencode')
      )
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Install pnpm and Node.js
        uses: pnpm/setup@v1
        with:
          version: 11
          runtime: node@24
          cache: true

      - name: Run OpenCode
        uses: anomalyco/opencode/github@latest
        env:
          OPENCODE_API_KEY: ${{ secrets.OPENCODE_API_KEY }}
        with:
          model: opencode-go/deepseek-v4-pro
