name: Validate-PR
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    name: Validate PR

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install pnpm and Node.js
        uses: pnpm/setup@v1
        with:
          version: 11
          runtime: node@24
          cache: true

      - name: Format Check
        run: pnpm dprint

      - name: Lint
        run: pnpm oxlint

      - name: Stylelint
        run: pnpm stylelint

      - name: Test
        run: pnpm test
